# Generated by Django 3.1.3 on 2020-12-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_entry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='user',
        ),
    ]
